### PR TITLE
move examples to separate files

### PR DESCRIPTION
**Pull request by pkra**

### CODE REVIEW

**Comment by pkra** [comment]
@philschatz should I merge this?

**Comment by philschatz** [comment]
It's up to you. I found that splitting the HTML into separate little tests to be helpful in understanding the edits to the `html.sem` and `.cfg` files

**Comment by pkra** [comment]
Thanks, I meant this more in "is this ready?" -- I do want this in the repo :smile: 

I'll try to update liblouis before our meeting.

**Comment by philschatz** [comment]
oops, yes merge away!

**Comment by philschatz** [comment]
I just pushed my changes from today's session. I took the newer, nicer-organized .sem and .cfg files, pasted them in, removed some classes and added a few elements so that the tests would generate output similar to what was generated beforehand. 

Rob mentioned that the zoom call will not occur in the 2 weeks in the middle of Sept and that he is thinking of rescheduling them as folks start teaching during the workday.

**Comment by pkra** [comment]
Thanks, @philschatz!

**Pull request merged**
